### ISSUE TITLE
Call to function "file" failed: no file exists

### ISSUE THREAD

**Issue by hylaride** [juliosueiras/terraform-lsp#26]
I'm running into a minor issue with the file module in 0.9. Its not interpolating `${path.module}` and cant find the file:
```template = "${file("${path.module}/files/policies/cloudtrail_kms_policy.json.tpl")}"```

```Call to function "file" failed: no file exists at /files/policies/cloudtrail_kms_policy.json.tpl.Terraform```

This is within a terraform module instantiated as a source from a directory.

**Comment by DJAlPee** [comment]
Same with `templatefile` function.

If used in `locals {}` it does not complain...

**Comment by djsly** [comment]
```
values = [
    templatefile("${path.module}/values.yaml",
```

returns

`Call to function "templatefile" failed: no file exists at /values.yaml.`

**Comment by EmberQuill** [comment]
I'm having the same issue. It looks like `path.module` always evaluates as an empty string. Looked into the code a bit and it looks like it might actually be caused by Hashicorp's hclsyntax module? Not 100% sure, but I found the text of the error message [here](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/expression.go#L431).

**Comment by awilkins** [comment]
I think OP is half-right - the input parameter *is* being interpolated, because otherwise the `${path.module}` wouldn't show up in the string, I think the problem here is that the LSP isn't setting a value for `path.module` in the context when it's evaluating the file.

**Comment by awilkins** [comment]
Anyone who wants to test this, pull and build the PR branch, and replace

`~/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-lsp`

.. with the new binary.

**Comment by juliosueiras** [comment]
@awilkins two thing, A) the issue was already fixed in the latest master branch and B) tfstructs/main.go supply helper function and does main completion portion, tfstructs/diags.go is the actual error checker portion

**Comment by awilkins** [comment]
Ah... maybe it being fixed is a side-effect of me just having rebuilt master and updated my extension with it - going to revert and rebuild it and see.

**Comment by myroslavmail** [comment]
Issue has appeared to me when I mistaken in naming. A SIMPLE TYPE.
Please, double check what you type. I hope it will be helpful for someone.

**Comment by sysreport** [comment]
> @awilkins two thing, A) the issue was already fixed in the latest master branch 
@juliosueiras the issue allready exists in the master branch.

I have rebuild yesterday from the masterbranch and replace the terraform-lsp file in my VSC installation.
The only thing you fixed is the file function, not the templatefile function. on the templatefile function the issue still exists.

**Comment by juliosueiras** [comment]
@sysreport what do you mean? Can I see the code snippet? Since both file and template uses the same path logic so the error does not matter if is templatefile or file function

**Comment by sysreport** [comment]
@juliosueiras here is a example:
```
data "template_file" "setup" {
  template = templatefile("setup.sh.tpl", {
    hostname = "${lower(var.name)}"
  })
}
```
the setup.sh.tpl is in the same folder with the terraform file

**Comment by sysreport** [comment]
@juliosueiras and here is a example now with no errors, but this was a error before  i have rebuild the terraform-lsp.
```
provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "user"
      private_key = file("~/.ssh/key")
      host = self.public_ip
    }

    inline = [
      "chmod +x setup.sh",
      "sudo ./setup.sh",
    ]
  }
```
this code have actually no issues after the rebuild.

**Comment by juliosueiras** [comment]
@sysreport not sure if this is the issue, but the way I notice is that the no file error will happen if you are using a module or deeper terraform files(and not using something like path.module), since vscode auto default to root directory of the project

**Comment by sysreport** [comment]
@juliosueiras you right. 
with the following example works the self builded terraform-lsp
```
data "template_file" "setup" {
  template = templatefile("${path.module}/setup.sh.tpl", {
    hostname = "${lower(var.name)}"
  })
}
```
thx for your work and help

**Comment by juliosueiras** [comment]
this issue is resolved in the latest version
